# Generated by Django 3.1.1 on 2021-10-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='hero_image',
            field=models.CharField(default='static', max_length=100),
            preserve_default=False,
        ),
    ]
